engines:
  rubocop:
    enabled: true
  jslint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - spec/**
  - src/**
  - "**.rb"
  - "**.js"
exclude_paths:
- "assets/"

checks:
  identical-code:
    config:
      threshold: 25
  similar-code:
    config:
      threshold: 50